// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMAeWTMbyrumAItePZCu_Qr7ZncOd2kpY',
    appId: '1:965369654495:web:a54df9138b38efd0b6cd6a',
    messagingSenderId: '965369654495',
    projectId: 'rbchatapp-a3710',
    authDomain: 'rbchatapp-a3710.firebaseapp.com',
    storageBucket: 'rbchatapp-a3710.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBhSq23TssJiorn_cKEG8FNLWVg91B7M8',
    appId: '1:965369654495:android:cf7fbf26f383bffbb6cd6a',
    messagingSenderId: '965369654495',
    projectId: 'rbchatapp-a3710',
    storageBucket: 'rbchatapp-a3710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Q2lweP45hziQIcirBK9wWrUR5ktUMDw',
    appId: '1:965369654495:ios:919d8309b915fd97b6cd6a',
    messagingSenderId: '965369654495',
    projectId: 'rbchatapp-a3710',
    storageBucket: 'rbchatapp-a3710.appspot.com',
    iosBundleId: 'com.example.rbChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Q2lweP45hziQIcirBK9wWrUR5ktUMDw',
    appId: '1:965369654495:ios:919d8309b915fd97b6cd6a',
    messagingSenderId: '965369654495',
    projectId: 'rbchatapp-a3710',
    storageBucket: 'rbchatapp-a3710.appspot.com',
    iosBundleId: 'com.example.rbChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMAeWTMbyrumAItePZCu_Qr7ZncOd2kpY',
    appId: '1:965369654495:web:42143dbf41264a09b6cd6a',
    messagingSenderId: '965369654495',
    projectId: 'rbchatapp-a3710',
    authDomain: 'rbchatapp-a3710.firebaseapp.com',
    storageBucket: 'rbchatapp-a3710.appspot.com',
  );
}
